#!/bin/bash

echo
echo "FairyJS compressed version builder Copyright (C) 2011  Yuriy Zisn"
echo "This program comes with ABSOLUTELY NO WARRANTY."
echo "This is free software, and you are welcome to redistribute it"
echo "under certain conditions."

echo

LIC="/* FairyJS zysoft.github.com/FairyJS | github.com/zysoft/FairyJS/blob/master/LICENSE */"
LICE=${LIC////'\/'}
LICE=${LICE//'*'/'\*'}
LICE=${LICE//'|'/'\|'}

echo -ne "Bulding separate minified files..."

if [ ! -d "../min" ];
then
  mkdir "../min";
fi;

java -jar yuicompressor/build/yuicompressor*.jar -o ".js$:-min.js" ../src/fjs*

echo "Done"
echo -ne "Bulding All-In-One module...."

mv ../src/*-min.js ../min/

echo "$LIC" >../min/fjs-min.js
cat ../min/fjs_core-min.js >> ../min/fjs-min.js
find ../min -type f ! -name 'fjs_core-min.js' ! -name 'fjs-min.js' -exec cat {} \; >> ../min/fjs-min.js

find ../min -type f ! -name 'fjs-min.js' -exec sed -e "1s/^/$LICE\\
/" -i.bak {} \; 

rm ../min/*.bak

echo "Done"
echo